#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.xdd.entity
  mapperLocations: classpath:mapper/*.xml


---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/bitex_pro?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: yhq123456
    driver-class-name: com.mysql.jdbc.Driver

    server.port=8083
    #服务器配置
    spring.application.name：rabbitmq-hello-receiving
    #rabbitmq连接参数
    spring.rabbitmq.host=192.168.0.51
    spring.rabbitmq.port=5672
    spring.rabbitmq.username=admin
    spring.rabbitmq.password=admin
    #rabbitmq消息确认
    spring.rabbitmq.publisher-confirms=true
    spring.rabbitmq.publisher-returns=true
